/**
 * Question paper PDF template — Sprint 5 PROMPT 20.
 *
 * Renders the structured paper into a clean, printable, exam-style PDF.
 * No Vaasenk gradients — printable black ink only. Header with metadata,
 * numbered sections, numbered questions (with MCQ options indented), and a
 * footer with the syllabus attribution + Vaasenk wordmark.
 *
 * Uses `React.createElement` directly (no JSX) so the file can live in the
 * existing NestJS `commonjs` + non-JSX tsconfig without configuration churn.
 * @react-pdf/renderer accepts plain React elements identically to JSX output.
 */

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer';
import * as React from 'react';
import type { PaperPdfContext } from '../types';

const styles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 50,
    fontSize: 11,
    fontFamily: 'Helvetica',
    lineHeight: 1.45,
    color: '#000',
  },
  header: {
    marginBottom: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: '#000',
  },
  institutionName: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    textAlign: 'center',
    marginBottom: 4,
  },
  paperTitle: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    textAlign: 'center',
    marginBottom: 6,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
    fontSize: 10,
  },
  metaCell: {
    flexGrow: 1,
  },
  metaCellRight: {
    textAlign: 'right',
  },
  instructionsBlock: {
    marginBottom: 14,
    paddingHorizontal: 4,
    fontSize: 10.5,
    fontStyle: 'italic',
  },
  sectionHeader: {
    marginTop: 14,
    marginBottom: 8,
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    paddingVertical: 4,
    paddingHorizontal: 6,
    backgroundColor: '#EEEEEE',
  },
  sectionInstructions: {
    marginBottom: 6,
    fontSize: 10,
    fontStyle: 'italic',
    color: '#444',
  },
  question: {
    marginBottom: 8,
  },
  questionRow: {
    flexDirection: 'row',
  },
  questionNumber: {
    width: 22,
    fontFamily: 'Helvetica-Bold',
  },
  questionBody: {
    flexGrow: 1,
    flexShrink: 1,
  },
  questionText: {
    marginBottom: 3,
  },
  questionMarks: {
    fontSize: 9,
    fontStyle: 'italic',
    color: '#444',
  },
  optionsBlock: {
    marginTop: 3,
    marginLeft: 6,
  },
  optionLine: {
    marginBottom: 2,
    fontSize: 10.5,
  },
  footer: {
    position: 'absolute',
    bottom: 18,
    left: 50,
    right: 50,
    fontSize: 8.5,
    color: '#555',
    textAlign: 'center',
    borderTopWidth: 0.5,
    borderTopStyle: 'solid',
    borderTopColor: '#999',
    paddingTop: 6,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 18,
    right: 50,
    fontSize: 8.5,
    color: '#555',
  },
});

const OPTION_LABELS = ['A', 'B', 'C', 'D', 'E', 'F'];

/**
 * Tiny wrapper around `React.createElement` that accepts a typed props object
 * along with the React-special `key` attribute. We use `unknown` for the
 * inner type so the caller can pass either react-pdf style props or
 * react-pdf-svg props without TS quibbling at the boundary — the templates
 * stay readable, and the renderer enforces the real prop contract at render
 * time.
 */
function el(
  type: React.ElementType,
  props: Record<string, unknown> & { key?: string | number } = {},
  ...children: React.ReactNode[]
): React.ReactElement {
  // React.createElement's typings reject our props because `key` is special
  // and react-pdf's prop types don't include it. We're calling the runtime
  // contract which DOES accept `key` in the props bag.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return React.createElement(type as any, props as any, ...children);
}

export function PaperTemplate(ctx: PaperPdfContext): React.ReactElement {
  const { paper, classroom, institution, source } = ctx;

  const footerText =
    `Generated by Vaasenk · Syllabus: "${source.syllabusName}" v${source.syllabusVersion}` +
    (source.samplePaperNames.length > 0
      ? ` · Patterned after ${source.samplePaperNames.join(', ')}`
      : '');

  const pageNumberRenderer = (info: {
    pageNumber: number;
    totalPages: number;
  }): string => `Page ${info.pageNumber} of ${info.totalPages}`;

  return el(
    Document,
    {},
    el(
      Page,
      { size: 'A4', style: styles.page },

      // Header
      el(
        View,
        { style: styles.header, fixed: true },
        el(Text, { style: styles.institutionName }, institution.name),
        el(Text, { style: styles.paperTitle }, paper.title),
        el(
          View,
          { style: styles.metaRow },
          el(
            Text,
            { style: styles.metaCell },
            `Class: ${classroom.className}${classroom.sectionName ? ' — ' + classroom.sectionName : ''}`,
          ),
          el(
            Text,
            { style: { ...styles.metaCell, textAlign: 'center' } },
            `Subject: ${classroom.subjectName}`,
          ),
          el(
            Text,
            { style: { ...styles.metaCell, ...styles.metaCellRight } },
            `Max Marks: ${paper.totalMarks}` +
              (paper.durationMinutes
                ? ` · Time: ${paper.durationMinutes} min`
                : ''),
          ),
        ),
      ),

      // Instructions
      paper.structuredContent.instructions &&
        el(
          View,
          { style: styles.instructionsBlock },
          el(Text, {}, paper.structuredContent.instructions),
        ),

      // Sections
      ...paper.structuredContent.sections.map((section, sIdx) =>
        el(
          View,
          { key: `s-${sIdx}`, wrap: true },
          el(Text, { style: styles.sectionHeader }, section.name),
          section.instructions
            ? el(Text, { style: styles.sectionInstructions }, section.instructions)
            : null,
          ...section.questions.map((q, qIdx) =>
            el(
              View,
              { key: `s-${sIdx}-q-${qIdx}`, style: styles.question, wrap: false },
              el(
                View,
                { style: styles.questionRow },
                el(Text, { style: styles.questionNumber }, `${qIdx + 1}.`),
                el(
                  View,
                  { style: styles.questionBody },
                  el(
                    Text,
                    { style: styles.questionText },
                    `${q.text}   `,
                    el(
                      Text,
                      { style: styles.questionMarks },
                      `[${q.marks} mark${q.marks === 1 ? '' : 's'}]`,
                    ),
                  ),
                  q.options && q.options.length > 0
                    ? el(
                        View,
                        { style: styles.optionsBlock },
                        ...q.options.map((opt, oIdx) =>
                          el(
                            Text,
                            { key: `opt-${oIdx}`, style: styles.optionLine },
                            `${OPTION_LABELS[oIdx] ?? oIdx + 1}. ${opt}`,
                          ),
                        ),
                      )
                    : null,
                ),
              ),
            ),
          ),
        ),
      ),

      // Footer (rendered fixed on every page).
      el(Text, { style: styles.footer, fixed: true }, footerText),
      el(Text, { style: styles.pageNumber, render: pageNumberRenderer, fixed: true }),
    ),
  );
}
